Repository rcgsheffield/sheffield_hpc, pull requests merged in 2023-03, with the labels that each got.

#1655 Add fingerprints to Stanage SSH section.
  stanagepilot/stanage-connecting-ssh.rst
Labels: Enhancement

#1669 Correct 'Dependancies' to 'Dependencies'
  bessemer/software/apps/mathematica.rst
  bessemer/software/apps/matlab.rst
  bessemer/software/development/git.rst
  bessemer/software/parallel/openmpi.rst
  sharc/software/apps/ANTs.rst
  sharc/software/apps/flame.rst
  sharc/software/apps/foxit.rst
  sharc/software/apps/gatk.rst
  sharc/software/apps/itksnap.rst
  sharc/software/apps/lammps.rst
  sharc/software/apps/mathematica.rst
  sharc/software/apps/matlab.rst
  sharc/software/apps/plink.rst
  sharc/software/apps/taverna-cli.rst
  sharc/software/apps/vcftools.rst
  sharc/software/development/git.rst
  sharc/software/libs/scotch.rst
  sharc/software/parallel/mvapich2-intel.rst
  sharc/software/parallel/openmpi-gcc.rst
  sharc/software/parallel/openmpi-intel.rst
  sharc/software/parallel/openmpi-pgi.rst
  stanagepilot/software/apps/mathematica.rst
Labels: Documentation Error, dependencies

#1672 OpenFOAM on Stanage: no explicit PMIX selection needed now
  stanagepilot/software/apps/openfoam.rst
Labels: Enhancement, Stanage
