Repository rcgsheffield/sheffield_hpc, pull requests merged in 2023-12, with the labels that each got.

#1917 Correction for Github Actions pathing in Prod.
  _static/css/watermark.css
Labels: build bug

#1927 Move Jupyterhub into decom ShARC section.
  decommissioned/sharc/index.rst
  decommissioned/sharc/jupyterhub.rst
  decommissioned/sharc/jupyterhub/conda.rst
  decommissioned/sharc/jupyterhub/conn_res_req_start.rst
  decommissioned/sharc/jupyterhub/cpus_gpus.rst
  decommissioned/sharc/jupyterhub/issues.rst
  decommissioned/sharc/jupyterhub/jupyterlab_overview.rst
  decommissioned/sharc/jupyterhub/nb_usage.rst
  decommissioned/sharc/jupyterhub/quickstart.rst
  decommissioned/sharc/jupyterhub/sess_monit.rst
  decommissioned/sharc/jupyterhub/terminal.rst
  hpc/index.rst
Labels: Documentation Error, Enhancement, ShARC

#1928 Add watermark/ShARC decom warning to pages + scripts to insert said includes.
  decommissioned/add_watermark_line.sh
  decommissioned/sharc/add_sharc_decom_line.sh
  decommissioned/sharc/jupyterhub.rst
  decommissioned/sharc/jupyterhub/conda.rst
  decommissioned/sharc/jupyterhub/conn_res_req_start.rst
  decommissioned/sharc/jupyterhub/cpus_gpus.rst
  decommissioned/sharc/jupyterhub/issues.rst
  decommissioned/sharc/jupyterhub/jupyterlab_overview.rst
  decommissioned/sharc/jupyterhub/nb_usage.rst
  decommissioned/sharc/jupyterhub/quickstart.rst
  decommissioned/sharc/jupyterhub/sess_monit.rst
  decommissioned/sharc/jupyterhub/terminal.rst
Labels: Enhancement

#1929 Add missing flight command.
  hpc/flight-desktop.rst
Labels: Documentation Error, Enhancement

#1889 MobaXterm terminal: warn that causes issues w/ Stanage + MFA
  hpc/connecting.rst
Labels: Enhancement
