Repository rcgsheffield/sheffield_hpc, pull requests merged in 2023-05, with the labels that each got.

#1768 Switch from Sphinx 5 to 6
  requirements.txt
Labels: Enhancement

#1770 Refactor HPC gateway info to cut down on spurious access requests.
  hpc/hpcgateway.rst
Labels: Documentation Error, Enhancement, Stanage

#1762 Amend Stanage Fluent SMP job script.
  stanage/software/apps/ansys/fluent.rst
Labels: Documentation Error, Enhancement

#1761 Update to R docs ShARC
  sharc/software/apps/R.rst
Labels: Enhancement, ShARC

#1772 Fix broken diagram display on filestores page.
  hpc/filestore.rst
  images/Sheffield-HPC-Cluster-Storage-Selection-decision-tree.drawio.svg
Labels: build bug, Documentation Error

#1777 Amend FAQ account file transfer instructions.
  FAQs.rst
Labels: Documentation Error

#1785 1784 update ansys multi core license restrictions
  FAQs.rst
  bessemer/software/apps/ansys/fluent.rst
  bessemer/software/apps/ansys/index.rst
  bessemer/software/apps/ansys/ls-dyna.rst
  bessemer/software/apps/ansys/mechanical.rst
  bessemer/software/apps/ansysem.rst
  referenceinfo/imports/software/ansys/ansys-license-restrictions.rst
  sharc/software/apps/ansys/fluent.rst
  sharc/software/apps/ansys/index.rst
  sharc/software/apps/ansys/ls-dyna.rst
  sharc/software/apps/ansys/mechanical.rst
  sharc/software/apps/ansysem.rst
  stanage/software/apps/ansys/fluent.rst
  stanage/software/apps/ansys/index.rst
Labels: Enhancement

#1775 Update OpenFOAM Stanage
  stanage/software/apps/openfoam.rst
Labels: Enhancement, Stanage

#1790 Promote use of ~ and/or $HOME
  hpc/filestore.rst
Labels: Enhancement, Stanage

#1794 Small correction toolchains on Stanage
  stanage/software/development/toolchains.rst
Labels: Stanage

#1783 1781 Document LAMMPS on Stanage
  sharc/software/apps/lammps.rst
  stanage/software/apps/lammps.rst
Labels: Enhancement, Stanage
