Repository rcgsheffield/sheffield_hpc, pull requests merged in 2024-07, with the labels that each got.

#2154 Update libsndfile command for readability
  stanage/software/libs/libsndfile.rst
Labels: Enhancement

#2144 Add netCDF on Stanage
  stanage/software/libs/netcdf.rst
Labels: Enhancement

#2160 El9 matlab docs
  stanage/software/apps/matlab.rst
Labels: Enhancement, EL9-beta

#2164 Boost doc for EL9
  stanage/software/libs/boost.rst
Labels: EL9-beta

#2169 Update GEOS EL9 doc
  stanage/software/libs/geos.rst
Labels: EL9-beta

#2182 Update xvfb versions EL9
  stanage/software/apps/xvfb.rst
Labels: EL9-beta

#2185 Update Vasp versions EL9
  stanage/software/apps/vasp.rst
Labels: EL9-beta

#2184 Update R versions EL9
  stanage/software/apps/R.rst
Labels: EL9-beta

#2187 Update ncdu versions for el9
  stanage/software/apps/ncdu.rst
Labels: EL9-beta

#2191 libunistring version changes
  stanage/software/libs/libunistring.rst
Labels: EL9-beta

#2193 Cmake docs el9 cdk
  stanage/software/development/cmake.rst
Labels: EL9-beta

#2192 Scalapack docs el9 cdk
  referenceinfo/admins/software.rst
  stanage/software/libs/scalapack.rst
Labels: EL9-beta

#2178 Cudnn el9 docs
  stanage/software/libs/cudnn.rst
Labels: EL9-beta

#2176 HDF5 el9 docs
  stanage/software/libs/hdf5.rst
Labels: EL9-beta

#2175 IMKL el9 documentation
  stanage/software/libs/imkl.rst
Labels: EL9-beta

#2197 Gromacs docs el9 cdk
  stanage/software/apps/gromacs.rst
Labels: EL9-beta

#2196 Vasp docs el9 sbatch directives correction cdk
  stanage/software/apps/vasp.rst
Labels: EL9-beta

#2195 Update openmpi versions EL9
  stanage/software/parallel/openmpi.rst
Labels: EL9-beta

#2190 Update OpenBLAS versions EL9
  stanage/software/libs/blas.rst
  stanage/software/libs/openblas.rst
Labels: EL9-beta

#2198 Update udunits EL9 docs
  stanage/software/libs/udunits.rst
Labels: EL9-beta

#2199 Update GSL docs for EL9
  stanage/software/libs/gsl.rst
Labels: EL9-beta

#2200 Update netCDF for EL9 docs
  stanage/software/libs/netcdf.rst
Labels: EL9-beta

#2202 Update IMPI EL9 doc
  stanage/software/parallel/impi.rst
Labels: EL9-beta

#2201 Update libsndfile znver3 for EL9 docs
  stanage/software/libs/libsndfile.rst
Labels: EL9-beta

#2212 Amend warning to show the current year.
  global.rst
Labels: Enhancement
