Repository rcgsheffield/sheffield_hpc, pull requests merged in 2024-05, with the labels that each got.

#2089 Poor connectivity
  FAQs.rst
  hpc/mfa.rst
  referenceinfo/imports/staying_connected.rst
Labels: Enhancement, Formatting

#2106 Add email support template
  help.rst
Labels: Enhancement

#2110 Fix typo in FAQ
  FAQs.rst
Labels: Documentation Error

#2103 Change SMP limit in Memory Allocation Limits Table
  referenceinfo/imports/scheduler/memory_allocation_limits_table_import.rst
Labels: Documentation Error

#2113 Add Lua module file
  hpc/installing-software.rst
  referenceinfo/environment-modules/creating-custom-modulefiles.rst
Labels: Enhancement
