Repository rcgsheffield/sheffield_hpc, pull requests merged in 2024-04, with the labels that each got.

#2065 Add some further guidance in comments for README and conf.py
  README.rst
  conf.py
Labels: Enhancement

#2080 Add Windows Terminal
  hpc/connecting.rst
  images/windows-terminal-profiles.png
  images/windows-terminal.png
  referenceinfo/connecting-ssh/index.rst
  referenceinfo/connecting-ssh/mobaxterm.rst
  referenceinfo/connecting-ssh/windows_terminal.rst
  referenceinfo/index.rst
Labels: CMS related

#2082 Fix formatting
  stanage/software/libs/PETSc.rst
Labels: Documentation Error

#2075 change $USER to YOUR_USERNAME and $CLUSTER_NAME to CLUSTER_NAME
  hpc/connecting.rst
Labels: Formatting

#2079 Flesh out why no sudo FAQ item, minor corrections to FAQ page separators.
  FAQs.rst
Labels: Documentation Error, Enhancement

#2083 Fix typos
  referenceinfo/connecting-ssh/windows_terminal.rst
Labels: Documentation Error

#2085 Add GSL Stanage
  stanage/software/libs/gsl.rst
Labels: Stanage
