Repository rcgsheffield/sheffield_hpc, pull requests merged in 2024-01, with the labels that each got.

#1937 Add info on Bessemer + Stanage JDK versions
  bessemer/software/apps/java.rst
  stanage/software/apps/java.rst
Labels: Enhancement, Bessemer, Stanage

#1940 Stanage: add znver3 Java builds
  stanage/software/apps/java.rst
Labels: Enhancement, Stanage

#1941 Add Slurm sattach info
  hpc/scheduler/index.rst
Labels: Enhancement

#1943 Shift SGE Job submission info to ShARC section.
  decommissioned/sharc/sge.rst
  hpc/scheduler/index.rst
Labels: Enhancement, ShARC

#1950 Move MFA news into news section
  index.rst
  newsletter/20231201.rst
  newsletter/index.rst
  newsletter/mfa-update-21-10-2021.rst
Labels: proposal

#1951 Amend --user=$USER to --me where appropriate.
  hpc/scheduler/index.rst
  referenceinfo/imports/scheduler/SLURM/common_commands/squeue_usage_import.rst
Labels: Enhancement

#1962 Add flight port forwarding password note
  hpc/flight-desktop.rst
Labels: Documentation Error, Enhancement, proposal

#1971 Add custom Google search.
  _templates/searchbox.html
  conf.py
Labels: Enhancement
