Repository rcgsheffield/sheffield_hpc, pull requests merged in 2024-02, with the labels that each got.

#1982 Update FAQs.rst - correct spelling error.
  FAQs.rst
Labels: Documentation Error

#1987 Add custom google search readme info.
  README.rst
Labels: Enhancement

#1992 Add inline warning about the need for interactive sessions.
  hpc/flight-desktop.rst
Labels: Enhancement, proposal

#1957 Add resetenv path
  FAQs.rst
Labels: Enhancement
